// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4xY_Z54qPcvah1Q98YMKB4oX4XOMFH8',
    appId: '1:48753616272:web:812341f8681de63ed33f15',
    messagingSenderId: '48753616272',
    projectId: 'new-revenue-7846e',
    authDomain: 'new-revenue-7846e.firebaseapp.com',
    storageBucket: 'new-revenue-7846e.firebasestorage.app',
    measurementId: 'G-XVRPH65DCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7JLtKXuZzQImmDoi8ywhmEOqSgI4IOw',
    appId: '1:48753616272:android:9696e0ce037d6686d33f15',
    messagingSenderId: '48753616272',
    projectId: 'new-revenue-7846e',
    storageBucket: 'new-revenue-7846e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceHzjKFHAK2Ckmp5h1g3OJBJbP0m4BNU',
    appId: '1:48753616272:ios:a951103053a0c45fd33f15',
    messagingSenderId: '48753616272',
    projectId: 'new-revenue-7846e',
    storageBucket: 'new-revenue-7846e.firebasestorage.app',
    iosBundleId: 'com.example.newRevenue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceHzjKFHAK2Ckmp5h1g3OJBJbP0m4BNU',
    appId: '1:48753616272:ios:a951103053a0c45fd33f15',
    messagingSenderId: '48753616272',
    projectId: 'new-revenue-7846e',
    storageBucket: 'new-revenue-7846e.firebasestorage.app',
    iosBundleId: 'com.example.newRevenue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU4xY_Z54qPcvah1Q98YMKB4oX4XOMFH8',
    appId: '1:48753616272:web:3dfb6101fd9bcbbed33f15',
    messagingSenderId: '48753616272',
    projectId: 'new-revenue-7846e',
    authDomain: 'new-revenue-7846e.firebaseapp.com',
    storageBucket: 'new-revenue-7846e.firebasestorage.app',
    measurementId: 'G-QVTDXQYQ41',
  );
}
